version: 2.1

orbs:
      aws-s3: circleci/aws-s3@1.0.0 #imports the s3 orb in the circleci namespace

jobs:
      build:
            docker:
                  - image: 'circleci/python:2.7'
            steps:
                  - checkout
                  - run:
                          name: Check branch to set s3 bucket path
                          command: |
                              echo ${CIRCLE_BRANCH}
                              if [ "${CIRCLE_BRANCH}" == "testing" ]; then
                                    echo 'here on testing'
                                    echo 'export S3_BUCKET_PATH="testing"' >> $BASH_ENV
                              else if ["${CIRCLE_BRANCH}" == "master"]; then
                                    echo 'here on master'
                                    echo 'export S3_BUCKET_PATH="production"' >> $BASH_ENV
                              else
                                    echo 'here else'
                                    echo 'export S3_BUCKET_PATH=test-$(echo ${CIRCLE_SHA1} | cut -c -7)/' >> $BASH_ENV
                              fi
                              echo ${S3_BUCKET_PATH}
                  - aws-s3/copy:
                          from: '*.html'
                          #to: 's3://${AWS_BUCKET}/'
                          to: 's3://${AWS_BUCKET}/${S3_BUCKET_PATH}/'