version: 2.1

orbs:
      aws-s3: circleci/aws-s3@1.0.0 #imports the s3 orb in the circleci namespace

workflows:
      build-test-deploy:
            jobs:
                  - deploy2s3: # a sample job that would be defined above.
                          steps:
                                - aws-s3/copy: #invokes the sync command declared in the s3 orb
                                        from: .
                                        to: 's3://${AWS_BUCKET}/test-$(echo $CIRCLE_SHA1 | cut -c -7)'
                                        overwrite: true